LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := hook
LOCAL_SRC_FILES := libhook.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include
include $(PREBUILT_STATIC_LIBRARY)


include $(CLEAR_VARS)
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include
LOCAL_LDLIBS += -llog
LOCAL_STATIC_LIBRARIES := libhook
APP_ALLOW_MISSING_DEPS =true
LOCAL_MODULE    := JniAttack
LOCAL_SRC_FILES := attack.cpp
include $(BUILD_SHARED_LIBRARY)
