/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_herbwen_myjnitest_MainActivity */

#ifndef _Included_com_herbwen_myjnitest_MainActivity
#define _Included_com_herbwen_myjnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_herbwen_myjnitest_MainActivity
 * Method:    hook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_herbwen_myjnitest_MainActivity_hook
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_herbwen_myjnitest_MainActivity_hookPuts
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
