/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_herbwen_myjnitest_RegisterNativeHook */

#ifndef _Included_com_herbwen_myjnitest_RegisterNativeHook
#define _Included_com_herbwen_myjnitest_RegisterNativeHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_herbwen_myjnitest_RegisterNativeHook
 * Method:    hook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_herbwen_myjnitest_RegisterNativeHook_hook
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
